from pathlib import Path

p = Path('docs/index.html')
s = p.read_text(encoding='utf-8')

MARKER = 'DIVERGENCE_V2_ANALOG'
if MARKER in s:
    print('divergence v2 already applied')
    raise SystemExit(0)

old_controls = '''<div class="controls">
<label class="tiny">指数<br><select id="divIndex" onchange="renderDivergence()"><option value="sp500">S&P 500</option><option value="nasdaq">Nasdaq Composite</option><option value="dow">Dow Jones</option></select></label>
<label class="tiny">观察窗口<br><select id="divWindow" onchange="renderDivergence()"><option value="5">5个交易日</option><option value="10">10个交易日</option><option value="20" selected>20个交易日</option></select></label>
<label class="tiny">图表区间<br><select id="divRange" onchange="renderDivergence()"><option value="1y">1年</option><option value="3y" selected>3年</option><option value="5y">5年</option><option value="all">全部</option></select></label>
</div>'''

new_controls = '''<div class="controls" data-feature="DIVERGENCE_V2_ANALOG">
<label class="tiny">指数<br><select id="divIndex" onchange="renderDivergence()"><option value="sp500">S&P 500</option><option value="nasdaq">Nasdaq Composite</option><option value="dow">Dow Jones</option></select></label>
<label class="tiny">观察窗口<br><select id="divWindow" onchange="renderDivergence()"><option value="5">5个交易日</option><option value="10">10个交易日</option><option value="20" selected>20个交易日</option></select></label>
<label class="tiny">背离区间开始<br><input id="divStart" type="date" onchange="onDivDateChange()"></label>
<label class="tiny">背离区间结束<br><input id="divEnd" type="date" onchange="onDivDateChange()"></label>
<label class="tiny">显示粒度<br><select id="divGran" onchange="renderDivergence()"><option value="day">日</option><option value="week">周</option><option value="month">月</option><option value="year">年</option></select></label>
<label class="tiny">快捷区间<br><select id="divQuick" onchange="applyDivQuickRange(this.value)"><option value="3m">近3个月</option><option value="6m">近6个月</option><option value="1y">近1年</option><option value="3y" selected>近3年</option><option value="5y">近5年</option><option value="all">全部</option><option value="custom">自定义</option></select></label>
</div>'''

if old_controls not in s:
    raise SystemExit('divergence controls anchor not found')
s = s.replace(old_controls, new_controls, 1)

matrix_anchor = '<div class="panel"><h3>三大指数当前背离矩阵</h3>'
new_panels = '''<div class="panel" style="margin-top:12px"><h3>背离区间分布</h3><div class="note">统计严格使用你上面选择的背离起止区间；日 / 周 / 月 / 年只改变图表显示粒度，不改变 5D / 10D / 20D 交易日背离定义。</div><div class="histStats" id="divRangeStats"></div></div>

<div class="panel" style="margin-top:12px"><h3>历史相似形态拟合 · Analog Model</h3><div class="note">把当前综合评分、评分变化、指数短中期走势、波动、趋势效率与当前背离状态，与历史逐日状态做标准化近邻匹配。它回答“历史上最像现在的阶段后来走了多久、多久上破/下破、支撑和压力大约在哪里”。相似度不是上涨/下跌概率；当前历史评分仍含重建成分，所以本区只作探索研究。</div><div class="histStats" id="analogSummary"></div><div class="contribWrap"><div class="panel"><h3>当前支撑 / 压力与历史路径区间</h3><div id="analogLevels"></div></div><div class="panel"><h3>最相似历史案例</h3><div id="analogBest"></div></div></div><div class="tableWrap"><table class="tbl"><thead><tr><th>历史日期</th><th>相似度</th><th>当时关系</th><th>评分</th><th>未来20D最大上涨</th><th>未来20D最大下跌</th><th>关系变化</th><th>上破阻力</th><th>下破支撑</th></tr></thead><tbody id="analogBody"></tbody></table></div></div>

'''
if matrix_anchor not in s:
    raise SystemExit('divergence matrix anchor not found')
s = s.replace(matrix_anchor, new_panels + matrix_anchor, 1)

js_anchor = 'function filtered(){'
if js_anchor not in s:
    raise SystemExit('JS anchor not found')

js = r'''
// ===== DIVERGENCE_V2_ANALOG =====
function divMedian(a){const v=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!v.length)return null;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2}
function divQuantile(a,q){const v=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!v.length)return null;const p=(v.length-1)*q,lo=Math.floor(p),hi=Math.ceil(p);return lo===hi?v[lo]:v[lo]+(v[hi]-v[lo])*(p-lo)}
function divDateShift(date,amount,unit){const d=new Date(date+'T00:00:00Z');if(unit==='m')d.setUTCMonth(d.getUTCMonth()-amount);else d.setUTCFullYear(d.getUTCFullYear()-amount);return d.toISOString().slice(0,10)}
function applyDivQuickRange(v){const rows=buildHistoryRows();if(!rows.length)return;const end=rows[rows.length-1].date,s=document.querySelector('#divStart'),e=document.querySelector('#divEnd');e.value=end;if(v==='all')s.value=rows[0].date;else if(v==='3m')s.value=divDateShift(end,3,'m');else if(v==='6m')s.value=divDateShift(end,6,'m');else if(v==='1y')s.value=divDateShift(end,1,'y');else if(v==='3y')s.value=divDateShift(end,3,'y');else if(v==='5y')s.value=divDateShift(end,5,'y');renderDivergence()}
function onDivDateChange(){const q=document.querySelector('#divQuick');if(q)q.value='custom';renderDivergence()}
function resampleDivergence(rows,g){if(g==='day')return rows;const m=new Map();rows.forEach(r=>{let k;if(g==='week'){const d=new Date(r.date+'T00:00:00Z'),dow=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-dow);k=d.toISOString().slice(0,10)}else if(g==='month')k=r.date.slice(0,7);else k=r.date.slice(0,4);m.set(k,r)});return [...m.values()]}
function renderDivDistribution(series){const root=document.querySelector('#divRangeStats');if(!root)return;root.innerHTML='';const v=series.filter(x=>Number.isFinite(x.scoreDelta)&&Number.isFinite(x.indexRet)),n=v.length,top=v.filter(x=>x.divKind==='top_divergence'),bot=v.filter(x=>x.divKind==='bottom_divergence'),divs=[...top,...bot];let longest=0,run=0,last='';v.forEach(x=>{if(x.divKind===last&&(x.divKind==='top_divergence'||x.divKind==='bottom_divergence'))run++;else run=(x.divKind==='top_divergence'||x.divKind==='bottom_divergence')?1:0;last=x.divKind;longest=Math.max(longest,run)});const cards=[['有效交易日',String(n),'flat'],['顶部风险背离',n?fmt(100*top.length/n)+'%':'—','neg'],['底部修复背离',n?fmt(100*bot.length/n)+'%':'—','pos'],['背离平均强度',divs.length?fmt(mean(divs.map(x=>x.divStrength)))+'/100':'—','flat'],['最长连续背离',longest?longest+' 个交易日':'—','flat']];cards.forEach(v=>{const d=document.createElement('div');d.className='histStat';d.innerHTML='<small>'+v[0]+'</small><b class="'+v[2]+'">'+v[1]+'</b>';root.appendChild(d)})}
function divTrafficZone(s){if(!Number.isFinite(s))return 'na';return s>=65?'green':s>=55?'blue':s>=45?'yellow':'red'}
function divRet(rows,i,key,n){return i>=n&&Number.isFinite(rows[i]?.[key])&&Number.isFinite(rows[i-n]?.[key])?(rows[i][key]/rows[i-n][key]-1)*100:null}
function divScoreDelta(rows,i,n){return i>=n&&Number.isFinite(rows[i]?.score)&&Number.isFinite(rows[i-n]?.score)?rows[i].score-rows[i-n].score:null}
function divRv20(rows,i,key){if(i<20)return null;const rs=[];for(let j=i-19;j<=i;j++){if(j<1||!Number.isFinite(rows[j]?.[key])||!Number.isFinite(rows[j-1]?.[key]))return null;rs.push(rows[j][key]/rows[j-1][key]-1)}const m=mean(rs);if(m==null)return null;const sd=Math.sqrt(rs.reduce((z,x)=>z+(x-m)*(x-m),0)/Math.max(1,rs.length-1));return sd*Math.sqrt(252)*100}
function divEfficiency20(rows,i,key){if(i<20||!Number.isFinite(rows[i]?.[key])||!Number.isFinite(rows[i-20]?.[key]))return null;let path=0;for(let j=i-19;j<=i;j++){if(!Number.isFinite(rows[j]?.[key])||!Number.isFinite(rows[j-1]?.[key]))return null;path+=Math.abs(rows[j][key]/rows[j-1][key]-1)}const net=Math.abs(rows[i][key]/rows[i-20][key]-1);return path>0?net/path:null}
function divStructure(rows,i,key){const e=divEfficiency20(rows,i,key),r=divRet(rows,i,key,20);if(!Number.isFinite(e)||!Number.isFinite(r))return 'na';if(e<0.35)return 'range';return r>=0?'up':'down'}
function divFeature(rows,divSeries,i,key){return {score:rows[i]?.score,s5:divScoreDelta(rows,i,5),s20:divScoreDelta(rows,i,20),r5:divRet(rows,i,key,5),r20:divRet(rows,i,key,20),rv20:divRv20(rows,i,key),eff20:divEfficiency20(rows,i,key),strength:divSeries[i]?.divStrength,kind:divSeries[i]?.divKind,structure:divStructure(rows,i,key)}}
function divFutureOutcome(rows,divSeries,i,key){if(i<21||i>=rows.length-2||!Number.isFinite(rows[i]?.[key]))return null;const px=rows[i][key],prior=rows.slice(Math.max(0,i-20),i).map(r=>r[key]).filter(Number.isFinite);if(prior.length<10)return null;const resistance=Math.max(...prior),support=Math.min(...prior),zone=divTrafficZone(rows[i].score),kind=divSeries[i]?.divKind;let relationChange=null,zoneChange=null,upBreak=null,downBreak=null;const fut=[];for(let d=1;d<=60&&i+d<rows.length;d++){const r=rows[i+d],nxt=rows[i+d+1];if(Number.isFinite(r[key]))fut.push({d,p:r[key]});if(relationChange==null&&divSeries[i+d]&&divSeries[i+d].divKind!==kind&&nxt&&divSeries[i+d+1]&&divSeries[i+d+1].divKind!==kind)relationChange=d;if(zoneChange==null&&divTrafficZone(r.score)!==zone&&nxt&&divTrafficZone(nxt.score)!==zone)zoneChange=d;if(upBreak==null&&Number.isFinite(r[key])&&r[key]>resistance)upBreak=d;if(downBreak==null&&Number.isFinite(r[key])&&r[key]<support)downBreak=d}const f20=fut.filter(x=>x.d<=20).map(x=>(x.p/px-1)*100),f60=fut.map(x=>(x.p/px-1)*100);return {relationChange,zoneChange,upBreak,downBreak,maxUp20:f20.length?Math.max(...f20):null,maxDown20:f20.length?Math.min(...f20):null,maxUp60:f60.length?Math.max(...f60):null,maxDown60:f60.length?Math.min(...f60):null,support,resistance}}
function buildAnalogModel(rows,key,w){if(rows.length<140)return null;const ds=divergenceSeries(rows,key,w),cur=rows.length-1,cf=divFeature(rows,ds,cur,key),fields=[['score',1.5],['s5',1.0],['s20',1.35],['r5',0.8],['r20',1.2],['rv20',0.9],['eff20',0.7],['strength',0.9]];if(fields.some(([f])=>!Number.isFinite(cf[f])))return null;const raw=[];for(let i=60;i<rows.length-65;i++){const f=divFeature(rows,ds,i,key);if(fields.every(([x])=>Number.isFinite(f[x])))raw.push({i,f})}if(raw.length<30)return null;const stats={};fields.forEach(([f])=>{const a=raw.map(x=>x.f[f]),m=mean(a),sd=std(a);stats[f]={m,sd:sd||1}});raw.forEach(x=>{let z=0,ws=0;fields.forEach(([f,wt])=>{const d=(x.f[f]-cf[f])/stats[f].sd;z+=wt*d*d;ws+=wt});let dist=Math.sqrt(z/ws);if(cf.kind&&x.f.kind!==cf.kind)dist+=cf.kind.includes('divergence')?0.75:0.35;if(cf.structure!=='na'&&x.f.structure!==cf.structure)dist+=0.25;x.dist=dist;x.sim=100*Math.exp(-0.45*dist)});raw.sort((a,b)=>a.dist-b.dist);const chosen=[];for(const x of raw){if(chosen.every(y=>Math.abs(y.i-x.i)>=40)){const o=divFutureOutcome(rows,ds,x.i,key);if(o)chosen.push({...x,o});if(chosen.length>=5)break}}if(!chosen.length)return null;const currentOutcome=divFutureOutcome(rows,ds,cur,key);return {currentIndex:cur,currentFeature:cf,matches:chosen,currentLevels:currentOutcome,divSeries:ds}}
function daysLabel(vals,total){const v=vals.filter(Number.isFinite);if(!v.length)return '60D内未发生';const med=divMedian(v),q1=divQuantile(v,.25),q3=divQuantile(v,.75);return fmt(med)+'D · IQR '+fmt(q1)+'–'+fmt(q3)+' · '+v.length+'/'+total+'例'}
function renderAnalog(rows,key,w){const sum=document.querySelector('#analogSummary'),levels=document.querySelector('#analogLevels'),best=document.querySelector('#analogBest'),body=document.querySelector('#analogBody');if(!sum||!levels||!best||!body)return;sum.innerHTML=levels.innerHTML=best.innerHTML=body.innerHTML='';const m=buildAnalogModel(rows,key,w);if(!m){sum.innerHTML='<div class="empty">历史可比样本不足。</div>';return}const ms=m.matches,b=ms[0],idx=DIV_INDEX_LABELS[key]||key,cards=[['最相似历史锚点',b?bDate(rows,b.i):'—','flat'],['最高相似度',b?fmt(b.sim)+'/100':'—','flat'],['关系/背离变化',daysLabel(ms.map(x=>x.o.relationChange),ms.length),'flat'],['上破20D前高',daysLabel(ms.map(x=>x.o.upBreak),ms.length),'pos'],['下破20D前低',daysLabel(ms.map(x=>x.o.downBreak),ms.length),'neg'],['灯号区域变化',daysLabel(ms.map(x=>x.o.zoneChange),ms.length),'flat']];cards.forEach(v=>{const d=document.createElement('div');d.className='histStat';d.innerHTML='<small>'+v[0]+'</small><b class="'+v[2]+'">'+v[1]+'</b>';sum.appendChild(d)});const cur=rows[m.currentIndex],lv=m.currentLevels,downs=ms.map(x=>x.o.maxDown20).filter(Number.isFinite),ups=ms.map(x=>x.o.maxUp20).filter(Number.isFinite),lo=downs.length?cur[key]*(1+divMedian(downs)/100):null,hi=ups.length?cur[key]*(1+divMedian(ups)/100):null;levels.innerHTML='<div class="boxLine"><span>'+idx+' 当前</span><b>'+fmt(cur[key])+'</b></div><div class="boxLine"><span>20D历史支撑</span><b>'+fmt(lv?.support)+'</b></div><div class="boxLine"><span>20D历史压力</span><b>'+fmt(lv?.resistance)+'</b></div><div class="boxLine"><span>相似路径20D下沿中位</span><b>'+fmt(lo)+'</b></div><div class="boxLine"><span>相似路径20D上沿中位</span><b>'+fmt(hi)+'</b></div><div class="tiny">“相似路径上下沿”是把 Top 5 历史案例未来20日最大下跌/上涨的中位数映射到当前指数，不是硬支撑或目标价。</div>';best.innerHTML='<div class="boxLine"><span>日期</span><b>'+bDate(rows,b.i)+'</b></div><div class="boxLine"><span>相似度</span><b>'+fmt(b.sim)+'/100</b></div><div class="boxLine"><span>当时关系</span><b>'+((m.divSeries[b.i]||{}).divState||'—')+'</b></div><div class="boxLine"><span>当时评分</span><b>'+fmt(rows[b.i].score)+'</b></div><div class="boxLine"><span>未来20D最大上涨</span><b class="pos">'+pct(b.o.maxUp20)+'</b></div><div class="boxLine"><span>未来20D最大下跌</span><b class="neg">'+pct(b.o.maxDown20)+'</b></div><div class="boxLine"><span>关系变化</span><b>'+(b.o.relationChange==null?'60D内未发生':b.o.relationChange+'D')+'</b></div>';ms.forEach(x=>{const tr=document.createElement('tr'),d=m.divSeries[x.i]||{};tr.innerHTML='<td>'+bDate(rows,x.i)+'</td><td>'+fmt(x.sim)+'</td><td class="'+divergenceClass(d)+'">'+(d.divState||'—')+'</td><td>'+fmt(rows[x.i].score)+'</td><td class="pos">'+pct(x.o.maxUp20)+'</td><td class="neg">'+pct(x.o.maxDown20)+'</td><td>'+(x.o.relationChange==null?'—':x.o.relationChange+'D')+'</td><td>'+(x.o.upBreak==null?'—':x.o.upBreak+'D')+'</td><td>'+(x.o.downBreak==null?'—':x.o.downBreak+'D')+'</td>';body.appendChild(tr)})}
function bDate(rows,i){return rows[i]?.date||'—'}

// Override the original renderer with custom divergence interval + display granularity + analog model.
function renderDivergence(){const rows=buildHistoryRows();if(!rows.length)return;const key=document.querySelector('#divIndex')?.value||'sp500',w=Number(document.querySelector('#divWindow')?.value||20),s=document.querySelector('#divStart'),e=document.querySelector('#divEnd'),g=document.querySelector('#divGran')?.value||'day';const first=rows[0].date,last=rows[rows.length-1].date;if(s){s.min=first;s.max=last}if(e){e.min=first;e.max=last}if(e&&!e.value)e.value=last;if(s&&!s.value)s.value=divDateShift(last,3,'y');if(s&&s.value<first)s.value=first;if(e&&e.value>last)e.value=last;const start=s?.value||first,end=e?.value||last;const fullSeries=divergenceSeries(rows,key,w),selected=fullSeries.filter(x=>x.date>=start&&x.date<=end);renderDivSummary(selected,key,w);renderDivDistribution(selected);renderDivMatrix(rows);const selectedRows=rows.filter(x=>x.date>=start&&x.date<=end);renderLeadLag(selectedRows.length>30?selectedRows:rows);renderTurningPoints(selectedRows.length>60?selectedRows:rows);drawDivergence(resampleDivergence(selected,g));renderAnalog(rows,key,w)}
'''

s = s.replace(js_anchor, js + '\n' + js_anchor, 1)
p.write_text(s, encoding='utf-8')
print('patched divergence v2 interval + analog model')
